name: Deploy React Frontend to AWS

# Only run this script if code is pushed to main AND the changes are inside the blog-dashboard folder
on:
  push:
    branches:
      - main 
    paths:
      - 'blog-dashboard/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # This tells GitHub to run all terminal commands inside your frontend folder
    defaults:
      run:
        working-directory: ./blog-dashboard

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_GATEWAY_SECRET: ${{ secrets.VITE_GATEWAY_SECRET }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync Files to S3 Bucket
      run: aws s3 sync dist/ s3://blog-frontend-dashboard-ankyris-2026 --delete

    - name: Invalidate CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
